openapi: 3.0.3
info:
  title: Gloss Translation API
  description: |-
    This is the Gloss Translation API. 
    The frontend can be accessed at [https://gloss-translation.vercel.app]().
  version: 0.0.1
servers:
  - url: /api
paths:
  /auth/login:
    $ref: ./paths/auth.yml#login
  /auth/logout:
    $ref: ./paths/auth.yml#logout
  /auth/session:
    $ref: ./paths/auth.yml#session
  /users:
    $ref: ./paths/users.yml
  /users/{userId}:
    $ref: ./paths/user.yml
  /verses/{verseId}:
    $ref: ./paths/verse.yml
  /languages:
    $ref: ./paths/languages.yml
  /languages/{code}:
    $ref: ./paths/language.yml
  /languages/{code}/verses/{verseId}/translation:
    $ref: ./paths/translations.yml
  /languages/{code}/verses/{verseId}/glosses:
    $ref: ./paths/verse-glosses.yml
  /languages/{code}/words/{wordId}:
    $ref: ./paths/language-words.yml
  /languages/{code}/members:
    $ref: ./paths/language-members.yml
  /languages/{code}/members/{userId}:
    $ref: ./paths/language-member.yml
  /import/languages:
    $ref: ./paths/import/languages.yml
