openapi: 3.0.3
info:
  title: Gloss Translation API
  description: |-
    This is the Gloss Translation API. 
    The frontend can be accessed at [https://gloss-translation.vercel.app]().
  version: 0.0.1
servers:
  - url: https://gloss-translation-api.vercel.app/api
    description: Production server
  - url: http://localhost:4300/api
    description: Local server
paths:
  /verses/{verseId}/words:
    $ref: ./paths/words.yml
  /languages:
    $ref: ./paths/languages.yml
  /languages/{code}:
    $ref: ./paths/language.yml
  /languages/{code}/verses/{verseId}/translation:
    $ref: ./paths/translations.yml
  /languages/{code}/verses/{verseId}/glosses:
    $ref: ./paths/verse-glosses.yml
  /languages/{code}/words/{wordId}:
    $ref: ./paths/language-words.yml
