openapi: 3.0.3
info:
  title: Gloss Translation API
  description: |-
    This is the Gloss Translation API.
    The frontend can be accessed at [https://gloss-translation.vercel.app]().
  version: 0.0.1
servers:
  - url: /api
paths:
  /auth/login:
    $ref: ./paths/users/auth.yml#login
  /auth/logout:
    $ref: ./paths/users/auth.yml#logout
  /auth/session:
    $ref: ./paths/users/auth.yml#session
  /auth/invite:
    $ref: ./paths/users/auth.yml#invite
  /auth/forgot-password:
    $ref: ./paths/users/auth.yml#forgot-password
  /auth/reset-password:
    $ref: ./paths/users/auth.yml#reset-password
  /users:
    $ref: ./paths/users/users.yml
  /users/{userId}:
    $ref: ./paths/users/user.yml
  /email/verify:
    $ref: ./paths/users/verify-email.yml
  /verses/{verseId}:
    $ref: ./paths/translation/verse.yml
  /verses/{verseId}/lemma-resources:
    $ref: ./paths/translation/lemma-resources.yml
  /import/languages:
    $ref: ./paths/languages/import-languages.yml
  /languages:
    $ref: ./paths/languages/languages.yml
  /languages/{code}:
    $ref: ./paths/languages/language.yml
  /languages/{code}/import:
    $ref: ./paths/languages/languages-import.yml
  /languages/{code}/books/{bookId}/progress:
    $ref: ./paths/translation/book-progress.yml
  /languages/{code}/verses/{verseId}/translation:
    $ref: ./paths/translation/translations.yml
  /languages/{code}/verses/{verseId}/phrases:
    $ref: ./paths/translation/verse-phrases.yml
  /languages/{code}/verses/{verseId}/suggestions:
    $ref: ./paths/translation/verse-suggestions.yml
  /languages/{code}/verses/{verseId}/next-unapproved-verse:
    $ref: ./paths/translation/next-unapproved-verse.yml
  /languages/{code}/phrases:
    $ref: ./paths/languages/phrases.yml
  /languages/{code}/phrases/{phraseId}/gloss:
    $ref: ./paths/languages/phrase-gloss.yml
  /languages/{code}/phrases/{phraseId}/translator-note:
    $ref: ./paths/languages/phrase-translator-note.yml
  /languages/{code}/phrases/{phraseId}/footnote:
    $ref: ./paths/languages/phrase-footnote.yml
  /languages/{code}/glosses/bulk:
    $ref: ./paths/translation/bulk-update-glosses.yml
  /languages/{code}/members:
    $ref: ./paths/languages/language-members.yml
  /languages/{code}/members/{userId}:
    $ref: ./paths/languages/language-member.yml
