languageCode:
  name: code
  in: path
  description: IETF code of the language
  required: true
  schema:
    type: string
  example: es
verseId:
  name: verseId
  in: path
  description: The verse number within the chapter. In the format of `BBCCCVVV`. (**B**ook, **C**hapter, **V**erse)
  required: true
  schema:
    type: number
  example: 0201401
wordId:
  name: wordId
  in: path
  description: The word ID within the chapter. In the format of `BBCCCVVVWW`. (**B**ook, **C**hapter, **V**erse, **W**ord).
  required: true
  schema:
    type: number
  example: 020140101