openapi: 3.0.3
info:
  title: Gloss Translation API
  description: |-
    This is the Gloss Translation API. 
    The frontend can be accessed at [https://gloss-translation.vercel.app]().
  termsOfService: http://example.com/terms/ # TODO: Fill this in
  contact:
    email: need.email.here@example.com # TODO: Fill this in
  license:
    name: Apache 2.0 # TODO: Fill this in
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.0.1
servers:
  - url: https://gloss-translation-api.vercel.app/api
    description: Production server
  - url: http://localhost:4300/api
    description: Local server
tags:
  - name: health
    description: Get server health status.
  - name: language
    description: Access language metadata.
paths:
  /health:
    get:
      tags:
        - health
      responses:
        "200":
          description: Successful Operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  databaseConnection:
                    type: string
                    example: ok
  /language:
    get:
      tags:
        - language
      responses:
        "200":
          description: Successful Operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Language"
  /languages/{code}:
    get:
      tags:
        - language
      summary: Get a language by language code.
      description: Returns the metadata for a single language.
      operationId: getLanguageByCode
      parameters:
        - name: code
          in: path
          description: ISO 690-1 code of the language to return.
          required: true
          schema:
            type: string
          example: es
      responses:
        "200":
          description: Successful Operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Language"
        "400":
          description: Invalid language code supplied
        "404":
          description: Language not found
components:
  schemas:
    Language:
      required:
        - code
        - name
      type: object
      properties:
        code:
          type: string
          example: es
          description: The ISO 639-1 language code.
        name:
          type: string
          example: Español
  requestBodies:
    Language:
      description: Language object that needs to be added to the system.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Language"
