name: Deploy Landing to S3
on:
  push:
    branches:
      - main
    paths:
      - packages/landing/**
      - tailwind.base.json
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1

      - run: npm ci
      - run: npx nx build landing
      - run: aws s3 sync . s3://gbt-landing
        working-directory: ./dist/packages/landing
